import { Footer } from "@/components/app-router/footer/footer";
import NextAuthProvider from "@/components/app-router/next-auth-provider";
import { ReactQueryClientProvider } from "@/components/app-router/query-client-provider";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import { inter, overpass } from "@/styles/fonts";
import { getServerSession } from "next-auth";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body>
        <NextAuthProvider session={session}>
          <ReactQueryClientProvider>
            <Fonts>
              <div className="flex flex-col min-h-screen">
                {children}
                <Footer menu={null} />
              </div>
            </Fonts>
          </ReactQueryClientProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}

function Fonts({ children }: { children: React.ReactNode }) {
  return (
    <div
      className={`${inter.variable} ${overpass.variable} font-overpass antialiased`}
    >
      {children}
    </div>
  );
}
